### PR TITLE
Description field should be optional

### PR DESCRIPTION
**Pull request by bradyrenting**
Sometimes you have to fill in the description field when it's not neccessery, e.g. for a weekly meeting.

### CODE REVIEW

**Comment by MichielBier** [comment]
I agree, it is not mandatory in clickup, therefore it should not be in this project.

**Comment by gwleuverink** [comment]
Hi, thanks for your contribution.

I believe you are right forcing a description is an annoyance in some cases. 

From a managerial perspective I can also see the benefits of making it at least required to fill something because it makes it easier when writing up invoices.

I'm open to making the validation for this field optional by use of a setting. 

Would you be interested in contributing this feature?

**Comment by bradyrenting** [comment]
Sure! I have pushed my changes. The description field will be optional by default.

**Comment by gwleuverink** [comment]
Love it! It looks great. I'll test it this weekend. Expect a new release soon :)

**Comment by gwleuverink** [comment]
@bradyrenting Released in [v0.2.0](https://github.com/gwleuverink/clickup-time-tracker/releases/tag/v0.2.0) 🎉

**Pull request merged**
